# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3ed623e863dfeb435f5dae05cbaf98ff285febee2e8c67a0e8816db1cf3d9ae7f7c75b8935f2fd3323ec052da7fa756420704890501b63b13c3347d916362151

test:
  secret_key_base: fafcad44785743d2ff6110edfba534aa81858c8544b868390262cb0ff23171fb91bcf8a65aa3a2c0465b079c95c7796f32de7cb50834a927343619b114e17036

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
